[package]
name = "sauron"
version = "0.1.2"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "An html library for building client side webapps"
repository = "https://github.com/ivanceras/sauron"
documentation = "https://docs.rs/sauron"
readme = "README.md"
keywords = ["html", "dom", "web"]
edition = "2018"

[dependencies]
js-sys = "0.3"
sauron_vdom = "0.1.0"
maplit = "1.0.1"
wasm-bindgen = "0.2.40"
lazy_static = "1.0"


[dependencies.web-sys]
version = "0.3"
features = [
    "Comment",
    "console",
    "Document",
    "Element",
    "Event",
    "HtmlElement",
    "EventTarget",
    "KeyboardEvent",
    "HtmlCollection",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "MouseEvent",
    "Node",
    "NodeList",
    "Text",
    "CharacterData",
    "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.2.33"
console_error_panic_hook = "0.1.5"

[dev-dependencies.web-sys]
version = "0.3"
features = [
    "DomTokenList",
    "HtmlInputElement",
    "Event",
    "MouseEvent",
    "InputEvent",
    "console",
]

[workspace]
members = [
    "crates/sauron_vdom"
]

[replace]
"sauron_vdom:0.1.0" = { path = "crates/sauron_vdom" }
